<a href="https://colab.research.google.com/github/Halak29-6/AI_ML-Training-Batch1/blob/main/Homework/Numpy_numpyAdvanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# what is numpy ?

- num = numeric
- py = python

- numpy is scientific computing library for python
- Support large number of data in the form of multi- dimensional array and matrix
- use for mathematic calculation like linear algebra,random number capabilites



In [1]:
pip install numpy

In [5]:
import numpy as np

# 1d array



In [6]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [7]:
type(arr_1d)

numpy.ndarray

In [8]:
print('Dimentions of array :',arr_1d.ndim)

Dimentions of array : 1


#2D array


In [9]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
print('Dimension of array :',arr_2d.ndim)

Dimension of array : 2


In [ ]:
arr_1d.size

4

In [ ]:
arr_2d.shape  #row and columns

(2, 4)

In [ ]:
arr_1d.dtype

dtype('int64')

In [ ]:
arr_2d.dtype

dtype('int64')

In [11]:
mx_1s = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
ar_1d = np.ones(5)
print(ar_1d)

[1. 1. 1. 1. 1.]


In [ ]:
ar_1s = np.ones(5, dtype = int)
print(ar_1s)

[1 1 1 1 1]


In [ ]:
ar_0s = np.zeros(5)
print(ar_0s)

[0. 0. 0. 0. 0.]


In [ ]:
# np.empty

#Numpy funcs

In [13]:
ar_1d = np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
even_ar = np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


In [14]:
#linspace()
np.linspace(1,3,2)


array([1., 3.])

In [ ]:
#reshape()

ar_2d = ar_1d.reshape(3,4)
print(ar_2d)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
ar_3d = ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
#ravel()

ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#flatten()
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#transpose() - ro to column colume to row

ar.transpose()


array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [ ]:
#mathematical
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)

print(arr1)
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
np.dot(arr1,arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
arr1.max()

np.int64(9)

In [ ]:
arr1.argmax() #max index

np.int64(8)

In [ ]:
arr1.max(axis = 0)

array([7, 8, 9])

In [ ]:
arr1.max(axis = 1)

array([3, 6, 9])

In [20]:
mx = np.arange(1,26).reshape(5,5)
print(mx)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
mx[0] #row

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
mx[:,0:1].ndim

2

In [ ]:
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
list_1 = [1,2,3,4]
list_2 = [5,6,7,8]

In [ ]:
list_1 + list_2

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
arr1 + arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [ ]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [ ]:
import numpy as np
arr1d = np.array([1,2,3])
arr = np.array([11,25,37])
anss = np.vstack((arr1d,arr))
ans = arr1d+2
print(anss)

[[ 1  2  3]
 [11 25 37]]


In [ ]:
arr2d = np.array ( [[1,2,3],[4,5,6]])
arr2d2 = np.array([1,1,1])
ans = arr2d*arr2d2
print(ans)

[[1 2 3]
 [4 5 6]]


In [ ]:
#convert 2d to 3d array
ans = arr2d.reshape(2,3,1)
print(ans)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [ ]:
# create a 3d array
array_3d = np.array([[[4,5,6] , [7,8,9], [10,11,12]]])
array3d2 = np.array([5,5,5])
ans = array_3d*array3d2
print(ans)

[[[20 25 30]
  [35 40 45]
  [50 55 60]]]


In [ ]:
import numpy as np

var = np.array([7,5,3,-1,-4,0])
print( var)

neg = var[var<0]
print(neg)

pos = var[var>0]
print(pos)

[ 7  5  3 -1 -4  0]
[-1 -4]
[7 5 3]


In [ ]:
nums2d = np.array([[-9,8,-7],[6,-5,4]])
print("initial array: \n",nums2d)
#normal broadcasting

pos_nums = nums2d[nums2d>0]
print("\npositive nums:" , pos_nums)

neg_nums = nums2d[nums2d<0]
print("\nnegative nums: ",neg_nums)

print("------------\n------------")

# using masking
print("using masking")
pos_mask = nums2d>0
neg_mask = nums2d<0

pos_nums = nums2d[pos_mask]
neg_nums = nums2d[neg_mask]

print(pos_nums)
print(neg_nums)

initial array: 
 [[-9  8 -7]
 [ 6 -5  4]]

positive nums: [8 6 4]

negative nums:  [-9 -7 -5]
------------
------------
using masking
[8 6 4]
[-9 -7 -5]


In [ ]:
import numpy as np
arr = np.array([1,2,3])
print("\nRow Vector: \n" , arr)


arr_col = arr[:, np.newaxis]
print("\nColumn vector:\n", arr_col)




Row Vector: 
 [1 2 3]

Column vector:
 [[1]
 [2]
 [3]]


In [ ]:
dtype = [('name',"S10"),('age','i4'),('height' ,'f4')]
data = np.array( [('halak', 20, 154.5) , ('riya',22,157.8)], dtype=dtype)
print(data)


[(b'halak', 20, 154.5) (b'riya', 22, 157.8)]


In [ ]:
#finding Trignometry

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
np.sin(180)

np.float64(-0.8011526357338304)

In [ ]:
# string oprations

In [21]:
char_name = 'halak'
str_1 = 'dudiya'

In [22]:
np.char.add(char_name,str_1)

np.str_('halakdudiya')

In [23]:
np.char.upper(char_name)

array('HALAK', dtype='<U5')

In [24]:
np.char.center(str_1, 60, fillchar = '*')

array('***************************dudiya***************************',
      dtype='<U60')

In [25]:
np.char.split(str_1)

array(list(['dudiya']), dtype=object)

In [26]:
np.char.splitlines('hii there\ai-ml')

array(list(['hii there\x07i-ml']), dtype=object)

In [27]:
str1 = 'dmy'
str2 = 'DMY'

In [ ]:
np.char.join([(':','/')],[str1,str2])

array([['d:m:y', 'D/M/Y']], dtype='<U5')

In [28]:
np.char.equal(str1,str2)

array(False)

In [30]:
char_name = 'hello halak here ! '

In [31]:
np.char.replace(char_name,'dudiya', 'there')

array('hello halak here ! ', dtype='<U19')

In [32]:
char_name

'hello halak here ! '

#Broadcasting


In [ ]:
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([10, 20, 30])     # Shape (3,)

# Broadcasting over multiple axes
result = arr1 * arr2
print(result)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [ ]:
var = np.array([1,2,3])
print(var)

[1 2 3]


In [ ]:
var[1]

np.int64(2)

In [ ]:
index = [0,1]
var[index]

array([1, 2])